### ISSUE TITLE
link-latency meta 

### ISSUE THREAD

**Issue by caryan** [BBN-Q/APS2-TDM-Interconnect#10]
Keep track of link latency in a single issue.  With a 900MHz line rate or 90MHz byte clock we have 443ns link latency from TDM to APS2 with 300MHz user clocks on either side. The latency is spread as follows:

| section | latency (clocks) | latency (ns) |
| --- | --- | --- |
| tx fifo user -> byte clock | 1 wr + 3/4 rd | 41 |
| tx framing state machine | 4 | 44.4 |
| transmit SGII adapter | 1 | 11.1 |
| PCS/PMA core gmii_txd_int to txdata | 3 | 33.3 |
| 8b/10b encode-transmit-decode | ~15 | 177 |
| PCS/PMA rxdata to gmii_rxd_int | 6 | 66.6 |
| receive SGII adapter | 4 | 44.4 |
| rx deframing | 0 | 0 |
| rx fifo byte -> user clock | 1 wr + 3/4 rd | 24 |

Potential places to improve latency:
- [ ] remove SGMII adapter (#7)
- [ ] run TDM off of byte clock
- [ ] frame with 0x55, 0x55 header and treat first non 0x55 valid byte as first valid on receive - if we have a message protocol (see #8) with the first byte as the message type we could reserve 0x55
- [ ] roll our own PCS/PMA core
- [ ] roll our own 8b/10 encode
- [ ] faster line rate

**Comment by blakejohnson** [comment]
There seems to be some prior work in this area, for example:

http://iopscience.iop.org/article/10.1088/1748-0221/5/12/C12017/pdf
https://indico.cern.ch/event/113796/contributions/1321203/attachments/44369/63875/FixedLatency_poster.pdf
https://arxiv.org/pdf/1509.06637.pdf
